apiVersion: v1
kind: pod
metadata:
  name: nginx-pod
  namespace: roboshop
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80  

# kubectl apply -f pod.yaml
# kubectl gets pods -n roboshop
# kubectl exec -it nginx-pod -n roboshop -- bash    --> to login into the container.
# kubectl delete -f pod.yaml

# how to run multicontainers in single pod.

apiVersion: v1
kind: Pod 
metadata:
  name: nginx-os-pod
  namespace: roboshop
spec: 
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
    - name: os
      image: almalinux:8
      command: ["sleep", "600"]     

# kubectl exec -it nginx-os-pod -n roboshop -c os -- bash  ----> to login into the second container in the pod.   

# Two containers share the same network. So when you access the nginx container running in another container with curl localhost 

# you will get the nginx web page content that you have configured.



