apiVersion: v1
kind: secret
metadata:
  name: secret-pod
data:
  username: c3JpcmFtCg==
  password: YWJjMTIzCg==

---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx-secret-pod
spec: 
  containers:
    - name: nginx-secret-cntr
      image: nginx  
      envFrom:
        - secretRef:
            name: secret-pod

# kubectl apply -f secret.yaml            
# kubectl exec -it nginx-secret-pod -- bash ---> after entering inside the pod type env command there you can see the username and password.        
    