apiVersion: v1
kind: Pod
metadata: 
  name: configmap-pod
spec:
  containers:
    - name: configmap-pod
      image: nginx
      env:
      # In a Kubernetes Pod definition, the env section is used to set environment variables for the containers within the pod. 
      # Each environment variable is defined as a key-value pair. The "- name:" part is used to specify the name of the environment variable.
        - name: COURSE
          valueFrom:
            configMapKeyRef:
              name: course-config
              key: COURSE
        - name: PERSON
          valueFrom:
            configMapKeyRef:
              name: course-config
              key: TRAINER   
        - name: DURATION
          valueFrom:
            configMapKeyRef:
              name: course-config
              key: DURATION      

# kubectl apply -f configmap-pod.yaml
# kubectl exec -it configmap-pod -- bash ---> after login into the container type env command then it will show the key and values you
# have defined in the configmap.               

apiVersion: v1
kind: Pod
metadata: 
  name: direct-configmapref
spec:
  containers:
    - name: configmap-pod
      image: nginx
      envFrom:
        - configMapRef:
            name: course-config

